version: 0.0
os: linux

files:
  - source: /
    destination: /opt/apps

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
#   ApplicationStop:
#     - location: scripts/stop.sh
#       runas: root
